// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: plugins/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Plugin service messages
type GetTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypesRequest) Reset() {
	*x = GetTypesRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypesRequest) ProtoMessage() {}

func (x *GetTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypesRequest.ProtoReflect.Descriptor instead.
func (*GetTypesRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{0}
}

type GetTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*RegisteredType      `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypesResponse) Reset() {
	*x = GetTypesResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypesResponse) ProtoMessage() {}

func (x *GetTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypesResponse.ProtoReflect.Descriptor instead.
func (*GetTypesResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetTypesResponse) GetTypes() []*RegisteredType {
	if x != nil {
		return x.Types
	}
	return nil
}

type RegisteredType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SubType       string                 `protobuf:"bytes,2,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	Schema        []byte                 `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredType) Reset() {
	*x = RegisteredType{}
	mi := &file_plugins_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredType) ProtoMessage() {}

func (x *RegisteredType) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredType.ProtoReflect.Descriptor instead.
func (*RegisteredType) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *RegisteredType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegisteredType) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *RegisteredType) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntitySubType string                 `protobuf:"bytes,2,opt,name=entity_sub_type,json=entitySubType,proto3" json:"entity_sub_type,omitempty"`
	EntityData    []byte                 `protobuf:"bytes,3,opt,name=entity_data,json=entityData,proto3" json:"entity_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ValidateRequest) GetEntitySubType() string {
	if x != nil {
		return x.EntitySubType
	}
	return ""
}

func (x *ValidateRequest) GetEntityData() []byte {
	if x != nil {
		return x.EntityData
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntitySubType string                 `protobuf:"bytes,2,opt,name=entity_sub_type,json=entitySubType,proto3" json:"entity_sub_type,omitempty"`
	EntityData    []byte                 `protobuf:"bytes,3,opt,name=entity_data,json=entityData,proto3" json:"entity_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CreateRequest) GetEntitySubType() string {
	if x != nil {
		return x.EntitySubType
	}
	return ""
}

func (x *CreateRequest) GetEntityData() []byte {
	if x != nil {
		return x.EntityData
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntitySubType string                 `protobuf:"bytes,2,opt,name=entity_sub_type,json=entitySubType,proto3" json:"entity_sub_type,omitempty"`
	EntityData    []byte                 `protobuf:"bytes,3,opt,name=entity_data,json=entityData,proto3" json:"entity_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *DestroyRequest) GetEntitySubType() string {
	if x != nil {
		return x.EntitySubType
	}
	return ""
}

func (x *DestroyRequest) GetEntityData() []byte {
	if x != nil {
		return x.EntityData
	}
	return nil
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{9}
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ChangedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntitySubType string                 `protobuf:"bytes,2,opt,name=entity_sub_type,json=entitySubType,proto3" json:"entity_sub_type,omitempty"`
	EntityData    []byte                 `protobuf:"bytes,3,opt,name=entity_data,json=entityData,proto3" json:"entity_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedRequest) Reset() {
	*x = ChangedRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedRequest) ProtoMessage() {}

func (x *ChangedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedRequest.ProtoReflect.Descriptor instead.
func (*ChangedRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ChangedRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ChangedRequest) GetEntitySubType() string {
	if x != nil {
		return x.EntitySubType
	}
	return ""
}

func (x *ChangedRequest) GetEntityData() []byte {
	if x != nil {
		return x.EntityData
	}
	return nil
}

type ChangedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedResponse) Reset() {
	*x = ChangedResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedResponse) ProtoMessage() {}

func (x *ChangedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedResponse.ProtoReflect.Descriptor instead.
func (*ChangedResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ChangedResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ChangedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Logger service messages
type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{14}
}

// State service messages
type StateGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateGetRequest) Reset() {
	*x = StateGetRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateGetRequest) ProtoMessage() {}

func (x *StateGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateGetRequest.ProtoReflect.Descriptor instead.
func (*StateGetRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *StateGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StateGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceData  []byte                 `protobuf:"bytes,1,opt,name=resource_data,json=resourceData,proto3" json:"resource_data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateGetResponse) Reset() {
	*x = StateGetResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateGetResponse) ProtoMessage() {}

func (x *StateGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateGetResponse.ProtoReflect.Descriptor instead.
func (*StateGetResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *StateGetResponse) GetResourceData() []byte {
	if x != nil {
		return x.ResourceData
	}
	return nil
}

func (x *StateGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StateFindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateFindRequest) Reset() {
	*x = StateFindRequest{}
	mi := &file_plugins_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateFindRequest) ProtoMessage() {}

func (x *StateFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateFindRequest.ProtoReflect.Descriptor instead.
func (*StateFindRequest) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *StateFindRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type StateFindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourcesData [][]byte               `protobuf:"bytes,1,rep,name=resources_data,json=resourcesData,proto3" json:"resources_data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateFindResponse) Reset() {
	*x = StateFindResponse{}
	mi := &file_plugins_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateFindResponse) ProtoMessage() {}

func (x *StateFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateFindResponse.ProtoReflect.Descriptor instead.
func (*StateFindResponse) Descriptor() ([]byte, []int) {
	return file_plugins_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *StateFindResponse) GetResourcesData() [][]byte {
	if x != nil {
		return x.ResourcesData
	}
	return nil
}

func (x *StateFindResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugins_plugin_proto protoreflect.FileDescriptor

const file_plugins_plugin_proto_rawDesc = "" +
	"\n" +
	"\x14plugins/plugin.proto\x12\x05proto\"\x11\n" +
	"\x0fGetTypesRequest\"?\n" +
	"\x10GetTypesResponse\x12+\n" +
	"\x05types\x18\x01 \x03(\v2\x15.proto.RegisteredTypeR\x05types\"W\n" +
	"\x0eRegisteredType\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bsub_type\x18\x02 \x01(\tR\asubType\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\fR\x06schema\"{\n" +
	"\x0fValidateRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12&\n" +
	"\x0fentity_sub_type\x18\x02 \x01(\tR\rentitySubType\x12\x1f\n" +
	"\ventity_data\x18\x03 \x01(\fR\n" +
	"entityData\"(\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"y\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12&\n" +
	"\x0fentity_sub_type\x18\x02 \x01(\tR\rentitySubType\x12\x1f\n" +
	"\ventity_data\x18\x03 \x01(\fR\n" +
	"entityData\"&\n" +
	"\x0eCreateResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"z\n" +
	"\x0eDestroyRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12&\n" +
	"\x0fentity_sub_type\x18\x02 \x01(\tR\rentitySubType\x12\x1f\n" +
	"\ventity_data\x18\x03 \x01(\fR\n" +
	"entityData\"'\n" +
	"\x0fDestroyResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x10\n" +
	"\x0eRefreshRequest\"'\n" +
	"\x0fRefreshResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"z\n" +
	"\x0eChangedRequest\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12&\n" +
	"\x0fentity_sub_type\x18\x02 \x01(\tR\rentitySubType\x12\x1f\n" +
	"\ventity_data\x18\x03 \x01(\fR\n" +
	"entityData\"A\n" +
	"\x0fChangedResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\":\n" +
	"\n" +
	"LogRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"\r\n" +
	"\vLogResponse\"#\n" +
	"\x0fStateGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"M\n" +
	"\x10StateGetResponse\x12#\n" +
	"\rresource_data\x18\x01 \x01(\fR\fresourceData\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x10StateFindRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\"P\n" +
	"\x11StateFindResponse\x12%\n" +
	"\x0eresources_data\x18\x01 \x03(\fR\rresourcesData\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xee\x02\n" +
	"\rPluginService\x12;\n" +
	"\bGetTypes\x12\x16.proto.GetTypesRequest\x1a\x17.proto.GetTypesResponse\x12;\n" +
	"\bValidate\x12\x16.proto.ValidateRequest\x1a\x17.proto.ValidateResponse\x125\n" +
	"\x06Create\x12\x14.proto.CreateRequest\x1a\x15.proto.CreateResponse\x128\n" +
	"\aDestroy\x12\x15.proto.DestroyRequest\x1a\x16.proto.DestroyResponse\x128\n" +
	"\aRefresh\x12\x15.proto.RefreshRequest\x1a\x16.proto.RefreshResponse\x128\n" +
	"\aChanged\x12\x15.proto.ChangedRequest\x1a\x16.proto.ChangedResponse2\xc6\x02\n" +
	"\x13HostCallbackService\x12-\n" +
	"\x04Info\x12\x11.proto.LogRequest\x1a\x12.proto.LogResponse\x12.\n" +
	"\x05Debug\x12\x11.proto.LogRequest\x1a\x12.proto.LogResponse\x12-\n" +
	"\x04Warn\x12\x11.proto.LogRequest\x1a\x12.proto.LogResponse\x12.\n" +
	"\x05Error\x12\x11.proto.LogRequest\x1a\x12.proto.LogResponse\x126\n" +
	"\x03Get\x12\x16.proto.StateGetRequest\x1a\x17.proto.StateGetResponse\x129\n" +
	"\x04Find\x12\x17.proto.StateFindRequest\x1a\x18.proto.StateFindResponseB1Z/github.com/jumppad-labs/hclconfig/plugins/protob\x06proto3"

var (
	file_plugins_plugin_proto_rawDescOnce sync.Once
	file_plugins_plugin_proto_rawDescData []byte
)

func file_plugins_plugin_proto_rawDescGZIP() []byte {
	file_plugins_plugin_proto_rawDescOnce.Do(func() {
		file_plugins_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_plugin_proto_rawDesc), len(file_plugins_plugin_proto_rawDesc)))
	})
	return file_plugins_plugin_proto_rawDescData
}

var file_plugins_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_plugins_plugin_proto_goTypes = []any{
	(*GetTypesRequest)(nil),   // 0: proto.GetTypesRequest
	(*GetTypesResponse)(nil),  // 1: proto.GetTypesResponse
	(*RegisteredType)(nil),    // 2: proto.RegisteredType
	(*ValidateRequest)(nil),   // 3: proto.ValidateRequest
	(*ValidateResponse)(nil),  // 4: proto.ValidateResponse
	(*CreateRequest)(nil),     // 5: proto.CreateRequest
	(*CreateResponse)(nil),    // 6: proto.CreateResponse
	(*DestroyRequest)(nil),    // 7: proto.DestroyRequest
	(*DestroyResponse)(nil),   // 8: proto.DestroyResponse
	(*RefreshRequest)(nil),    // 9: proto.RefreshRequest
	(*RefreshResponse)(nil),   // 10: proto.RefreshResponse
	(*ChangedRequest)(nil),    // 11: proto.ChangedRequest
	(*ChangedResponse)(nil),   // 12: proto.ChangedResponse
	(*LogRequest)(nil),        // 13: proto.LogRequest
	(*LogResponse)(nil),       // 14: proto.LogResponse
	(*StateGetRequest)(nil),   // 15: proto.StateGetRequest
	(*StateGetResponse)(nil),  // 16: proto.StateGetResponse
	(*StateFindRequest)(nil),  // 17: proto.StateFindRequest
	(*StateFindResponse)(nil), // 18: proto.StateFindResponse
}
var file_plugins_plugin_proto_depIdxs = []int32{
	2,  // 0: proto.GetTypesResponse.types:type_name -> proto.RegisteredType
	0,  // 1: proto.PluginService.GetTypes:input_type -> proto.GetTypesRequest
	3,  // 2: proto.PluginService.Validate:input_type -> proto.ValidateRequest
	5,  // 3: proto.PluginService.Create:input_type -> proto.CreateRequest
	7,  // 4: proto.PluginService.Destroy:input_type -> proto.DestroyRequest
	9,  // 5: proto.PluginService.Refresh:input_type -> proto.RefreshRequest
	11, // 6: proto.PluginService.Changed:input_type -> proto.ChangedRequest
	13, // 7: proto.HostCallbackService.Info:input_type -> proto.LogRequest
	13, // 8: proto.HostCallbackService.Debug:input_type -> proto.LogRequest
	13, // 9: proto.HostCallbackService.Warn:input_type -> proto.LogRequest
	13, // 10: proto.HostCallbackService.Error:input_type -> proto.LogRequest
	15, // 11: proto.HostCallbackService.Get:input_type -> proto.StateGetRequest
	17, // 12: proto.HostCallbackService.Find:input_type -> proto.StateFindRequest
	1,  // 13: proto.PluginService.GetTypes:output_type -> proto.GetTypesResponse
	4,  // 14: proto.PluginService.Validate:output_type -> proto.ValidateResponse
	6,  // 15: proto.PluginService.Create:output_type -> proto.CreateResponse
	8,  // 16: proto.PluginService.Destroy:output_type -> proto.DestroyResponse
	10, // 17: proto.PluginService.Refresh:output_type -> proto.RefreshResponse
	12, // 18: proto.PluginService.Changed:output_type -> proto.ChangedResponse
	14, // 19: proto.HostCallbackService.Info:output_type -> proto.LogResponse
	14, // 20: proto.HostCallbackService.Debug:output_type -> proto.LogResponse
	14, // 21: proto.HostCallbackService.Warn:output_type -> proto.LogResponse
	14, // 22: proto.HostCallbackService.Error:output_type -> proto.LogResponse
	16, // 23: proto.HostCallbackService.Get:output_type -> proto.StateGetResponse
	18, // 24: proto.HostCallbackService.Find:output_type -> proto.StateFindResponse
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_plugins_plugin_proto_init() }
func file_plugins_plugin_proto_init() {
	if File_plugins_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_plugin_proto_rawDesc), len(file_plugins_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugins_plugin_proto_goTypes,
		DependencyIndexes: file_plugins_plugin_proto_depIdxs,
		MessageInfos:      file_plugins_plugin_proto_msgTypes,
	}.Build()
	File_plugins_plugin_proto = out.File
	file_plugins_plugin_proto_goTypes = nil
	file_plugins_plugin_proto_depIdxs = nil
}
