// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/jumppad-labs/xcl/plugins"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProviderResolver creates a new instance of MockProviderResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderResolver {
	mock := &MockProviderResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderResolver is an autogenerated mock type for the ProviderResolver type
type MockProviderResolver struct {
	mock.Mock
}

type MockProviderResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderResolver) EXPECT() *MockProviderResolver_Expecter {
	return &MockProviderResolver_Expecter{mock: &_m.Mock}
}

// GetProviderForResource provides a mock function for the type MockProviderResolver
func (_mock *MockProviderResolver) GetProviderForResource(resource any) plugins.ProviderAdapter {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderForResource")
	}

	var r0 plugins.ProviderAdapter
	if returnFunc, ok := ret.Get(0).(func(any) plugins.ProviderAdapter); ok {
		r0 = returnFunc(resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugins.ProviderAdapter)
		}
	}
	return r0
}

// MockProviderResolver_GetProviderForResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderForResource'
type MockProviderResolver_GetProviderForResource_Call struct {
	*mock.Call
}

// GetProviderForResource is a helper method to define mock.On call
//   - resource any
func (_e *MockProviderResolver_Expecter) GetProviderForResource(resource interface{}) *MockProviderResolver_GetProviderForResource_Call {
	return &MockProviderResolver_GetProviderForResource_Call{Call: _e.mock.On("GetProviderForResource", resource)}
}

func (_c *MockProviderResolver_GetProviderForResource_Call) Run(run func(resource any)) *MockProviderResolver_GetProviderForResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProviderResolver_GetProviderForResource_Call) Return(providerAdapter plugins.ProviderAdapter) *MockProviderResolver_GetProviderForResource_Call {
	_c.Call.Return(providerAdapter)
	return _c
}

func (_c *MockProviderResolver_GetProviderForResource_Call) RunAndReturn(run func(resource any) plugins.ProviderAdapter) *MockProviderResolver_GetProviderForResource_Call {
	_c.Call.Return(run)
	return _c
}
