// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jumppad-labs/xcl/plugins"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProviderAdapter creates a new instance of MockProviderAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderAdapter {
	mock := &MockProviderAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderAdapter is an autogenerated mock type for the ProviderAdapter type
type MockProviderAdapter struct {
	mock.Mock
}

type MockProviderAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderAdapter) EXPECT() *MockProviderAdapter_Expecter {
	return &MockProviderAdapter_Expecter{mock: &_m.Mock}
}

// Changed provides a mock function for the type MockProviderAdapter
func (_mock *MockProviderAdapter) Changed(ctx context.Context, oldEntityData []byte, newEntityData []byte) (bool, error) {
	ret := _mock.Called(ctx, oldEntityData, newEntityData)

	if len(ret) == 0 {
		panic("no return value specified for Changed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte) (bool, error)); ok {
		return returnFunc(ctx, oldEntityData, newEntityData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte) bool); ok {
		r0 = returnFunc(ctx, oldEntityData, newEntityData)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, []byte) error); ok {
		r1 = returnFunc(ctx, oldEntityData, newEntityData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderAdapter_Changed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Changed'
type MockProviderAdapter_Changed_Call struct {
	*mock.Call
}

// Changed is a helper method to define mock.On call
//   - ctx context.Context
//   - oldEntityData []byte
//   - newEntityData []byte
func (_e *MockProviderAdapter_Expecter) Changed(ctx interface{}, oldEntityData interface{}, newEntityData interface{}) *MockProviderAdapter_Changed_Call {
	return &MockProviderAdapter_Changed_Call{Call: _e.mock.On("Changed", ctx, oldEntityData, newEntityData)}
}

func (_c *MockProviderAdapter_Changed_Call) Run(run func(ctx context.Context, oldEntityData []byte, newEntityData []byte)) *MockProviderAdapter_Changed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProviderAdapter_Changed_Call) Return(b bool, err error) *MockProviderAdapter_Changed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProviderAdapter_Changed_Call) RunAndReturn(run func(ctx context.Context, oldEntityData []byte, newEntityData []byte) (bool, error)) *MockProviderAdapter_Changed_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockProviderAdapter
func (_mock *MockProviderAdapter) Create(ctx context.Context, entityData []byte) ([]byte, error) {
	ret := _mock.Called(ctx, entityData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, entityData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, entityData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, entityData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderAdapter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProviderAdapter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entityData []byte
func (_e *MockProviderAdapter_Expecter) Create(ctx interface{}, entityData interface{}) *MockProviderAdapter_Create_Call {
	return &MockProviderAdapter_Create_Call{Call: _e.mock.On("Create", ctx, entityData)}
}

func (_c *MockProviderAdapter_Create_Call) Run(run func(ctx context.Context, entityData []byte)) *MockProviderAdapter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProviderAdapter_Create_Call) Return(bytes []byte, err error) *MockProviderAdapter_Create_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProviderAdapter_Create_Call) RunAndReturn(run func(ctx context.Context, entityData []byte) ([]byte, error)) *MockProviderAdapter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockProviderAdapter
func (_mock *MockProviderAdapter) Destroy(ctx context.Context, entityData []byte, force bool) error {
	ret := _mock.Called(ctx, entityData, force)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, bool) error); ok {
		r0 = returnFunc(ctx, entityData, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProviderAdapter_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockProviderAdapter_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - entityData []byte
//   - force bool
func (_e *MockProviderAdapter_Expecter) Destroy(ctx interface{}, entityData interface{}, force interface{}) *MockProviderAdapter_Destroy_Call {
	return &MockProviderAdapter_Destroy_Call{Call: _e.mock.On("Destroy", ctx, entityData, force)}
}

func (_c *MockProviderAdapter_Destroy_Call) Run(run func(ctx context.Context, entityData []byte, force bool)) *MockProviderAdapter_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProviderAdapter_Destroy_Call) Return(err error) *MockProviderAdapter_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProviderAdapter_Destroy_Call) RunAndReturn(run func(ctx context.Context, entityData []byte, force bool) error) *MockProviderAdapter_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockProviderAdapter
func (_mock *MockProviderAdapter) Init(state plugins.State, functions plugins.ProviderFunctions, logger plugins.Logger) error {
	ret := _mock.Called(state, functions, logger)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(plugins.State, plugins.ProviderFunctions, plugins.Logger) error); ok {
		r0 = returnFunc(state, functions, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProviderAdapter_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockProviderAdapter_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - state plugins.State
//   - functions plugins.ProviderFunctions
//   - logger plugins.Logger
func (_e *MockProviderAdapter_Expecter) Init(state interface{}, functions interface{}, logger interface{}) *MockProviderAdapter_Init_Call {
	return &MockProviderAdapter_Init_Call{Call: _e.mock.On("Init", state, functions, logger)}
}

func (_c *MockProviderAdapter_Init_Call) Run(run func(state plugins.State, functions plugins.ProviderFunctions, logger plugins.Logger)) *MockProviderAdapter_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugins.State
		if args[0] != nil {
			arg0 = args[0].(plugins.State)
		}
		var arg1 plugins.ProviderFunctions
		if args[1] != nil {
			arg1 = args[1].(plugins.ProviderFunctions)
		}
		var arg2 plugins.Logger
		if args[2] != nil {
			arg2 = args[2].(plugins.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProviderAdapter_Init_Call) Return(err error) *MockProviderAdapter_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProviderAdapter_Init_Call) RunAndReturn(run func(state plugins.State, functions plugins.ProviderFunctions, logger plugins.Logger) error) *MockProviderAdapter_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockProviderAdapter
func (_mock *MockProviderAdapter) Refresh(ctx context.Context, entityData []byte) ([]byte, error) {
	ret := _mock.Called(ctx, entityData)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, entityData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, entityData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, entityData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderAdapter_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockProviderAdapter_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - entityData []byte
func (_e *MockProviderAdapter_Expecter) Refresh(ctx interface{}, entityData interface{}) *MockProviderAdapter_Refresh_Call {
	return &MockProviderAdapter_Refresh_Call{Call: _e.mock.On("Refresh", ctx, entityData)}
}

func (_c *MockProviderAdapter_Refresh_Call) Run(run func(ctx context.Context, entityData []byte)) *MockProviderAdapter_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProviderAdapter_Refresh_Call) Return(bytes []byte, err error) *MockProviderAdapter_Refresh_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProviderAdapter_Refresh_Call) RunAndReturn(run func(ctx context.Context, entityData []byte) ([]byte, error)) *MockProviderAdapter_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProviderAdapter
func (_mock *MockProviderAdapter) Update(ctx context.Context, entityData []byte) ([]byte, error) {
	ret := _mock.Called(ctx, entityData)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]byte, error)); ok {
		return returnFunc(ctx, entityData)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []byte); ok {
		r0 = returnFunc(ctx, entityData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, entityData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderAdapter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProviderAdapter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - entityData []byte
func (_e *MockProviderAdapter_Expecter) Update(ctx interface{}, entityData interface{}) *MockProviderAdapter_Update_Call {
	return &MockProviderAdapter_Update_Call{Call: _e.mock.On("Update", ctx, entityData)}
}

func (_c *MockProviderAdapter_Update_Call) Run(run func(ctx context.Context, entityData []byte)) *MockProviderAdapter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProviderAdapter_Update_Call) Return(bytes []byte, err error) *MockProviderAdapter_Update_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockProviderAdapter_Update_Call) RunAndReturn(run func(ctx context.Context, entityData []byte) ([]byte, error)) *MockProviderAdapter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockProviderAdapter
func (_mock *MockProviderAdapter) Validate(ctx context.Context, entityData []byte) error {
	ret := _mock.Called(ctx, entityData)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, entityData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProviderAdapter_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockProviderAdapter_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - entityData []byte
func (_e *MockProviderAdapter_Expecter) Validate(ctx interface{}, entityData interface{}) *MockProviderAdapter_Validate_Call {
	return &MockProviderAdapter_Validate_Call{Call: _e.mock.On("Validate", ctx, entityData)}
}

func (_c *MockProviderAdapter_Validate_Call) Run(run func(ctx context.Context, entityData []byte)) *MockProviderAdapter_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProviderAdapter_Validate_Call) Return(err error) *MockProviderAdapter_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProviderAdapter_Validate_Call) RunAndReturn(run func(ctx context.Context, entityData []byte) error) *MockProviderAdapter_Validate_Call {
	_c.Call.Return(run)
	return _c
}
