// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockState creates a new instance of MockState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockState(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockState {
	mock := &MockState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockState is an autogenerated mock type for the State type
type MockState struct {
	mock.Mock
}

type MockState_Expecter struct {
	mock *mock.Mock
}

func (_m *MockState) EXPECT() *MockState_Expecter {
	return &MockState_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockState
func (_mock *MockState) Find(pattern string) ([]any, error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]any, error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []any); ok {
		r0 = returnFunc(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockState_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockState_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - pattern string
func (_e *MockState_Expecter) Find(pattern interface{}) *MockState_Find_Call {
	return &MockState_Find_Call{Call: _e.mock.On("Find", pattern)}
}

func (_c *MockState_Find_Call) Run(run func(pattern string)) *MockState_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockState_Find_Call) Return(vs []any, err error) *MockState_Find_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockState_Find_Call) RunAndReturn(run func(pattern string) ([]any, error)) *MockState_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockState
func (_mock *MockState) Get(key string) (any, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (any, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockState_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockState_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockState_Expecter) Get(key interface{}) *MockState_Get_Call {
	return &MockState_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockState_Get_Call) Run(run func(key string)) *MockState_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockState_Get_Call) Return(v any, err error) *MockState_Get_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockState_Get_Call) RunAndReturn(run func(key string) (any, error)) *MockState_Get_Call {
	_c.Call.Return(run)
	return _c
}
